spring:
  profiles:
    active: prod
  datasource:
    username: user
    password: pass
    url: jdbc:h2:mem:trucDB
  security:
    user:
      name: admin
      password: pass
      roles:
        - ADMIN
        - USER

ma:
  prop:
    custom: "ma petite propriété :)"
